In [1]:
## Random Numbers ##
import numpy as np

In [6]:
# Generate a single random float
random_float = np.random.rand()
print(random_float)

0.2384613947681835


In [3]:
# Generate an array of random floats
random_float_array = np.random.rand(5)
print(random_float_array)

[0.22604175 0.86757962 0.53560273 0.66176464 0.12286714]


In [4]:
# Generate a single random integer between 0 and 10
random_integer = np.random.randint(0,10)
print(random_integer)

5


In [7]:
# Generate an array of random integers between 0 and 10
random_ints = np.random.randint(0,10,size=5)
print(random_ints)

[4 4 4 9 5]


In [8]:
# Generate a single random number from a normal distribution
random_normal = np.random.randn()
print(random_normal)

-1.2823415307782629


In [11]:
# Generate an array of random numbers from a normal distribution
random_normal_array = np.random.randn(5)
print(random_normal_array)

[-0.71876738 -0.28195819  0.7310765   0.72097793 -0.09060564]


In [12]:
# Generate a single random number from a uniform distribution between 0 and 1
random_uniform = np.random.uniform(0,1)
print(random_uniform)

0.6205487382355215


In [13]:
# Generate an array of random numbers from a uniform distribution between 0 and 10
random_uniform_array = np.random.uniform(0,10,size=5)
print(random_uniform_array)

[6.96915119 4.22555552 3.47743261 2.15031463 5.01214066]


In [18]:
# Create an array to choose from
array = np.array([1,2,3,4,5])
print(array)

# Select a single random element from the array
random_choice = np.random.choice(array)
print(random_choice)

# Select multiple random elements from the array
random_choice_array = np.random.choice(array,size=5)
print(random_choice_array)

[1 2 3 4 5]
2
[3 1 1 4 4]


In [22]:
# Create a sequence
# ensure reproducibility of random numbers
sequence = np.arange(10)
print(sequence)

# Generate a random permutation of the sequence
random_permutation = np.random.permutation(sequence)
print(random_permutation)

[0 1 2 3 4 5 6 7 8 9]
[2 0 8 4 9 3 7 1 6 5]


In [26]:
# Set a random seed
np.random.seed(42)

# Generate the same random numbers
seeded_random_floats = np.random.rand(5)
print(seeded_random_floats)

[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
